# Generated by Django 5.0.4 on 2024-04-15 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology_unit1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bu1',
            name='q1',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
